version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ${SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    environment:
      - API_PORT=${API_PORT}
      - CONTAINER_NAMES=minecraft-bedrock,stopped-server,server-not-found
    ports:
      - ${API_PORT}:${API_PORT}
