version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - API_PORT=${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
