version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT}:3000
  client:
    build: ./client
    volumes:
      - ./client:/app
